name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Build and Tag
        uses: JasonEtco/build-and-tag-action@v2.0.1
        with:
          tag: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
