name: Release

on:
  push:
    tags:
      - '*'


jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Build
      - name: Build the file
        run: |
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/cleverio-pf100-feeder-card.js
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
  validate:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS Validate
        uses: hacs/action@main
        with:
          category: plugin